### ISSUE TITLE
Can you add an example project for iOS please?

### ISSUE THREAD

**Issue by 3lvis** [eternalstorms/ESSVideoShare-for-OS-X-Lion#1]

**Comment by eternalstorms** [comment]
Working on it :)

**Comment by eternalstorms** [comment]
sample project for iOS now available for download at http://eternalstorms.at/opensource/ESSVideoShare/essvideoshareios.zip

Also working on a How To for iOS as a Wiki Page (https://github.com/eternalstorms/ESSVideoShare-for-OS-X-Lion/wiki/How-To-for-iOS)

There's also a sample project for the Mac: http://eternalstorms.at/opensource/ESSVideoShare/esvideosharetestMac.zip
Wiki page for Mac: https://github.com/eternalstorms/ESSVideoShare-for-OS-X-Lion/wiki/How-To-for-OS-X-Lion

Thanks for your patience

**Comment by 3lvis** [comment]
AWESOME! Thanks (:
