### ISSUE TITLE
iOS7/6 oAuth issues

### ISSUE THREAD

**Issue by supudo** [eternalstorms/ESSVideoShare-for-OS-X-Lion#11]
First - fantastic work :+1: 

I'm having problems with Vimeo. On iOS 6 the test app works fine, after some tweaking on the navigation stuff it works on iOS 7 too. But on iOS 7 the access token call gives 

``` objc
401 Unauthorized - Invalid signature - The oauth_signature passed was not valid.
```

I've checked the oAuth code, but i can't figure how to fix it. It's probably something trivial. Is there a chance you could test it on iOS 7 and propose a fix?
I'll post a comment if i find a fix for it or a reason why it's happening.

Thank you!

**Comment by supudo** [comment]
Disregard that. The problem was in my TV :)

Great library!

**Comment by lovebytescodestings** [comment]
Can I ask what tweaks you made to the navigation to make it work in iOS 7? I was using this pre-iOS 7 and it was fantastic, but with the iOS 7 update I can no longer press the button to upload (or login if it's Youtube, Facebook can login because the login button is separate) and I can't for the life of me figure out how to make it work.

**Comment by supudo** [comment]
Well, one of the issues was (the one in my case) that the login controller cells did not use the new cell.contentView. Instead they add the UITextField directly in cell and afterwards they read it from cell. Should be cell.contentView addSubview ... and cell.contentView.subviews.
So, the problem was that on iOS 7 it can't find the text fields to get the data (user, pass, video title, etc.) instead of problems with oAuth.

**Comment by lovebytescodestings** [comment]
Did that also apply for the upload screens? I can't log in on Youtube, which sounds like it might be because of what you said above, but I can log in on Facebook because the login screen is handled by something else, but then I'm unable to upload.
